export const CLASS_NAMES = [
  'AbyssWalker',
  'Bishop',
  'BladeDancer',
  'DarkAvenger',
  'Destroyer',
  'ElementalSummoner',
  'ElvenElder',
  'Gladiator',
  'Hawkeye',
  'MoonlightSentinel',
  'Necromancer',
  'Overlord',
  'Paladin',
  'PhantomRanger',
  'PhantomSummoner',
  'PlainsWalker',
  'Prophet',
  'ShillenElder',
  'ShillenKnight',
  'Sorcerer',
  'SpellHowler',
  'SpellSinger',
  'Spoiler',
  'SwordSinger',
  'TempleKnight',
  'TreasureHunter',
  'Tyrant',
  'Warcryer',
  'Warlock',
  'Warlord',
  'Warsmith',
] as const;

export type ClassName = (typeof CLASS_NAMES)[number];
